name: NodeJS Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - feature/*
      - fix/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: |
          npm run lint
        env:
          CI: true

      - name: Build, and Tests
        run: |
          npm run build
        env:
          CI: true
